CREATE TABLE DB(
ID INT PRIMARY KEY AUTO_INCREMENT,
CODE varchar(100), 
NAME VARCHAR(200),
DRIVER VARCHAR(100),
URL VARCHAR(100),
USERNAME VARCHAR(100),
PASSWORD VARCHAR(100),
TYPE VARCHAR(100)
);
CREATE TABLE DB_DETAIL(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
VERSION_ID INT, 
TABLE_NAME VARCHAR(255),
COLUMN_NAME VARCHAR(255),
COLUMN_TYPE VARCHAR(100),
COLUMN_SIZE int
);
CREATE TABLE VERSION(
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
DB_ID INT,
DESCR VARCHAR(500),
CREATE_DATE VARCHAR(20)
);